import React, { useEffect, useRef, useState } from "react";
import { motion, AnimatePresence, useInView } from "motion/react";
import { Bold, Italic, Underline, Highlighter } from "lucide-react";

const sentences = [
  {
    text: "Discussion focused on Q3 roadmap.",
    highlight: false,
  },
  {
    text: "Next steps are documented and shared with attendees",
    highlight: true,
  },
  {
    text: "Review scheduled for Friday.",
    highlight: false,
  },
  {
    text: "Budget approved for infrastructure upgrades.",
    highlight: false,
  },
  {
    text: "Team velocity increased by 18% this sprint.",
    highlight: true,
  },
];

const highlights = [1, 4]; // indices to cycle through

export default function AiSummary() {
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: false, amount: 0.3 });

  const [activeHighlight, setActiveHighlight] = useState(0);
  const [showToolbar, setShowToolbar] = useState(true);

  useEffect(() => {
    if (!isInView) return;
    const t = setInterval(() => {
      setShowToolbar(false);
      setTimeout(() => {
        setActiveHighlight((p) => (p + 1) % highlights.length);
        setShowToolbar(true);
      }, 300);
    }, 2600);
    return () => clearInterval(t);
  }, [isInView]);

  const currentHighlightIndex = highlights[activeHighlight];

  return (
    <div ref={ref} className="w-full h-full flex flex-col p-4 gap-3">
      {/* Title */}
      <div className="flex items-center gap-2">
        <span className="text-xs font-semibold text-neutral-300 tracking-wide uppercase">
          Summary
        </span>
        <div className="h-px flex-1 bg-neutral-800" />
      </div>

      {/* Sentences */}
      <div className="flex-1 space-y-2.5">
        {sentences.map((s, i) => {
          const isHighlighted = i === currentHighlightIndex;

          return (
            <div key={i} className="relative">
              <AnimatePresence>
                {isHighlighted && showToolbar && (
                  <motion.div
                    initial={{ opacity: 0, y: -8, scale: 0.92 }}
                    animate={{ opacity: 1, y: -28, scale: 1 }}
                    exit={{ opacity: 0, y: -8, scale: 0.92 }}
                    transition={{ duration: 0.2 }}
                    className="absolute left-0 z-10 flex items-center gap-0.5 bg-neutral-800 border border-neutral-700 rounded-lg px-2 py-1 shadow-xl"
                  >
                    <Highlighter size={11} className="text-amber-400 mr-1" />
                    {[Bold, Italic, Underline].map((Icon, j) => (
                      <button
                        key={j}
                        className="w-5 h-5 flex items-center justify-center rounded hover:bg-neutral-700 text-neutral-400 hover:text-neutral-200 transition-colors"
                      >
                        <Icon size={10} />
                      </button>
                    ))}
                  </motion.div>
                )}
              </AnimatePresence>

              <motion.p
                animate={{
                  backgroundColor: isHighlighted
                    ? "rgba(59, 130, 246, 0.15)"
                    : "rgba(0,0,0,0)",
                  color: isHighlighted
                    ? "rgb(219, 234, 254)"
                    : i % 2 === 0
                      ? "rgb(163, 163, 163)"
                      : "rgb(115, 115, 115)",
                }}
                transition={{ duration: 0.35 }}
                className={`text-xs leading-relaxed rounded-md px-1.5 py-0.5 -mx-1.5 transition-all ${
                  isHighlighted ? "ring-1 ring-blue-500/30" : ""
                }`}
              >
                {s.text}
              </motion.p>
            </div>
          );
        })}
      </div>

      {/* AI badge */}
      <div className="flex items-center gap-1.5 mt-auto">
        <div className="w-4 h-4 rounded-full bg-blue-600/20 border border-blue-500/30 flex items-center justify-center">
          <span className="text-[8px] text-blue-400 font-bold">AI</span>
        </div>
        <span className="text-[10px] text-neutral-600">
          Generated by AI · Updated just now
        </span>
      </div>
    </div>
  );
}
